gems: [jekyll-paginate]

#Permalinks
permalink: "/:title"


highlighter: pygments

# Setup
title:               matt batista
tagline:             'Web dev for hire!'
description:         'Web dev for hire!'
url:                 https://sirmatt.github.io

# About/contact
author:
  name:              'matt batista'
  url:               https://twitter.com/mattoflegend
  email:             mattbatista@me.com

paginate:            1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/sirmatt/sirmatt.github.io

# This is the list of pages to include in the header of the website.
pages_list: {'about': '/about', 'contact': '/contact', 'archive':'/archive', 'feed':'/atom.xml'}
