# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

gems: [jekyll-paginate]

# Setup
title:               Matt Batista
tagline:             Friendly neighborhood web developer
url:                 http://sirmatt.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Batista
  url:               https://twitter.com/mattoflegend
  email:             mattbatista@me.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sirmatt/sirmatt.github.io
